/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dms.xtender;

import com.dms.xtender.Entity.DmsResponse.DmsResponse;
import com.dms.xtender.Entity.DmsResponse.Payload;
import com.dms.xtender.Entity.SapResponse.SapMessage;
import com.dms.xtender.Entity.SapResponse.SapResponse;
import com.dms.xtender.Utils.LogMessage;
import com.google.gson.Gson;
import com.squareup.okhttp.FormEncodingBuilder;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;
import com.squareup.okhttp.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.dms.xtender.Utils.Constant;
import com.google.gson.JsonSyntaxException;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingWorker;

/**
 *
 * @author 0395
 */
public class MainForm extends javax.swing.JFrame {
    private LogMessage LogWriter;
    private int APP_STATE;
    private Payload TransferPayload;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("DMS X-tender");

        txtUid.setText(String.valueOf(EntryPoint.user.getUid()));
        txtName.setText(EntryPoint.user.getName());
        LogWriter = LogMessage.GetInstance(txtProgressLog);
        
        APP_STATE = Constant.READ_STATE;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalRows = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCompCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBusDate = new javax.swing.JTextField();
        txtPstDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSySource = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIntId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnTransferSAP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProgressLog = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Header Information"));

        jLabel1.setText("TOTALROW");

        txtTotalRows.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTotalRows.setEnabled(false);

        jLabel2.setText("COMP_CODE");

        txtCompCode.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtCompCode.setEnabled(false);

        jLabel3.setText("BUS_DATE");

        txtBusDate.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtBusDate.setEnabled(false);

        txtPstDate.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtPstDate.setEnabled(false);

        jLabel4.setText("PST_DATE");

        jLabel5.setText("SY_SOURCE");

        txtSySource.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtSySource.setEnabled(false);

        jLabel6.setText("INT_ID");

        txtIntId.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtIntId.setEnabled(false);

        jLabel7.setText("UID");

        txtUid.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtUid.setEnabled(false);

        txtName.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtName.setEnabled(false);

        jLabel8.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSySource, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(txtBusDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalRows, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(txtPstDate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(txtCompCode))
                            .addComponent(jLabel6)
                            .addComponent(txtIntId, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtName))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPstDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIntId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSySource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTransferSAP.setText("GET FROM DMS");
        btnTransferSAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferSAPActionPerformed(evt);
            }
        });

        txtProgressLog.setBackground(new java.awt.Color(0, 0, 102));
        txtProgressLog.setColumns(20);
        txtProgressLog.setForeground(new java.awt.Color(255, 255, 255));
        txtProgressLog.setRows(5);
        jScrollPane1.setViewportView(txtProgressLog);

        jMenu1.setText("DMS Xtender");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnTransferSAP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnTransferSAP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        (new SettingForm()).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnTransferSAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferSAPActionPerformed
        btnTransferSAP.setEnabled(false);
        
        if(APP_STATE == Constant.READ_STATE){
            SwingWorker sw = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    getDataFromDms();
                    return null;
                }

                @Override
                public void done() {
                    btnTransferSAP.setEnabled(true);
                }
            };
            
            sw.execute();
            return;
        }
        
        if(APP_STATE == Constant.PUSH_STATE){
            SwingWorker sw2 = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    transferToSap();
                    return null;
                }
                
                @Override
                public void done() {
                    btnTransferSAP.setEnabled(true);
                }
            };
            
            sw2.execute();
            return;
        }
    }//GEN-LAST:event_btnTransferSAPActionPerformed

    private void transferToSap()
    {
        String SIT_ADDRESS = EntryPoint.config.getSitEndPoint();
        Gson gson = new Gson();
        
        RequestBody requestBody = new FormEncodingBuilder()
                .add("json", gson.toJson(TransferPayload))
                .add("functionName", EntryPoint.config.getFunctionName())
                .add("intId", EntryPoint.config.getIntId())
                .add("idField", EntryPoint.config.getIdField())
                .build();
        
        LogWriter.Add("Sending with payload..");
        LogWriter.Add("JSON: " + gson.toJson(TransferPayload));
        LogWriter.Add("functionName : " + EntryPoint.config.getFunctionName());
        LogWriter.Add("intId : " + EntryPoint.config.getIntId());
        LogWriter.Add("idField : " + EntryPoint.config.getIdField());
        
        LogWriter.Add(".");
        LogWriter.Add(".");
        LogWriter.Add("WAITING RESPONSE..");
        OkHttpClient client = new OkHttpClient();
        client.setConnectTimeout(1, TimeUnit.HOURS); // connect timeout
        client.setReadTimeout(1, TimeUnit.HOURS);    // socket timeout

        Request request = new Request.Builder()
            .url(SIT_ADDRESS)
            .post(requestBody)
            .build();
        
        Response response = null;
        try {
            response = client.newCall(request).execute();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            LogWriter.Add("########################");
            LogWriter.Add("TRANSFER DATA FAILED..");
            LogWriter.Add("message : "+ ex.getMessage());
        }

        if(response == null){
            LogWriter.Add("###### Process stoped!! ######");
            return;
        }

        if(response.code() != 200){
            LogWriter.Add("###### Process stoped!! ######");
            LogWriter.Add("response : " + response.code() + ", " + response.message());
            return;
        }
        
        try {
            gson = new Gson();
            SapResponse[] sapResponse = gson.fromJson(response.body().string(), SapResponse[].class);
            
            if(!sapResponse[0].isSuccess()){
                SapMessage[] msgs = sapResponse[0].getMsgs();
                for (SapMessage msg : msgs) {
                    LogWriter.Add(msg.getMSG_REF1() + " - " + msg.getMSG_STR());
                }

                LogWriter.Add("###### Process stoped!! ######");
                LogWriter.Add("response : " + response.code() + ", " + response.message());
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            LogWriter.Add("message : " + ex.getMessage());
        } catch (JsonSyntaxException th){
            LogWriter.Add("message : " + th.getMessage());
        }
        
        LogWriter.Add("######################");
        LogWriter.Add("TRANSFER SUCCESS..");
        
        LogWriter.Add(".");
        LogWriter.Add(".");
        LogWriter.Add("CREATING HISTORY..");
        String HISTORY_API = EntryPoint.config.GetDmsAddress() + EntryPoint.config.getSaveData();
        
        RequestBody requestBody2 = new FormEncodingBuilder()
                .add("uid", String.valueOf(EntryPoint.user.getUid()))
                .build();
        
        try
        {
            Request request2 = new Request.Builder()
                .url(HISTORY_API)
                .post(requestBody2)
                .build();
            Response response2 = null;
            try {
                response2 = client.newCall(request2).execute();
            } catch (IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                LogWriter.Add("message : "+ ex.getMessage());
            }

            if(response2 == null){
                LogWriter.Add("###### Process stoped!! ######");
                return;
            }

            if(response2.code() != 200){
                LogWriter.Add("###### Process stoped!! ######");
                LogWriter.Add("response : " + response2.code() + ", " + response2.message());
                return;
            }

            LogWriter.Add(".");
            LogWriter.Add(".");
            LogWriter.Add("#################################");
            LogWriter.Add("DONE..");
            LogWriter.Add(response2.body().toString());
            APP_STATE = Constant.READ_STATE;
        } catch (Exception ex)
        {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            LogWriter.Add("message : "+ ex.getMessage());
        }
    }
    
    private void getDataFromDms(){
        String FETCH_ADDRESS = EntryPoint.config.GetDmsAddress() + EntryPoint.config.getFetchData();
        LogWriter.Add("Fetching data from DMS..");

        RequestBody requestBody = new FormEncodingBuilder()
                .add("uid", String.valueOf(EntryPoint.user.getUid()))
                .build();

        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
            .url(FETCH_ADDRESS)
            .post(requestBody)
            .build();

        Response response = null;
        try {
            response = client.newCall(request).execute();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            LogWriter.Add("Fetching data failed..");
            LogWriter.Add(ex.getMessage());
        }

        if(response == null){
            LogWriter.Add("###### Process stoped!! ######");
            return;
        }

        if(response.code() != 200){
            LogWriter.Add("###### Process stoped!! ######");
            LogWriter.Add("response : " + response.code() + ", " + response.message());
            return;
        }

        try {
            Gson gson = new Gson();
            DmsResponse dmsResponse = gson.fromJson(response.body().string(), DmsResponse.class);
            
            if(!dmsResponse.getInfo()){
                JOptionPane.showMessageDialog(null, dmsResponse.getMessage());
                LogWriter.Add("###### Process stoped!! ######");
                LogWriter.Add("response : " + response.code() + ", " + response.message());
                return;
            }
            
            TransferPayload = dmsResponse.getItems();
            txtTotalRows.setText(TransferPayload.getTOTALROW());
            txtCompCode.setText(TransferPayload.getCOMP_CODE());
            txtBusDate.setText(TransferPayload.getBUS_DATE());
            txtPstDate.setText(TransferPayload.getPST_DATE());
            txtIntId.setText(TransferPayload.getINT_ID());
            txtSySource.setText(TransferPayload.getSY_SOURCE());            
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        LogWriter.Add(".");
        LogWriter.Add(".");
        LogWriter.Add("########################");
        LogWriter.Add("FETCHING DATA SUCCESS..");

        LogWriter.Add(".");
        LogWriter.Add(".");
        LogWriter.Add("########################");
        LogWriter.Add("READY TO TRANSFER..");

        btnTransferSAP.setText("TRANSFER TO SAP");
        APP_STATE = Constant.PUSH_STATE;        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferSAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBusDate;
    private javax.swing.JTextField txtCompCode;
    private javax.swing.JTextField txtIntId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtProgressLog;
    private javax.swing.JTextField txtPstDate;
    private javax.swing.JTextField txtSySource;
    private javax.swing.JTextField txtTotalRows;
    private javax.swing.JTextField txtUid;
    // End of variables declaration//GEN-END:variables
}
